name: Hospital Management System CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build Eureka Server
        working-directory: backend/discovery-server-Eureka
        run: mvn clean package -DskipTests

      - name: Build Config Server
        working-directory: backend/config server
        run: mvn clean package -DskipTests

      - name: Build Auth Service
        working-directory: backend/auth-service
        run: mvn clean package -DskipTests

      - name: Build Patient Service
        working-directory: backend/patient-service
        run: mvn clean package -DskipTests

      - name: Build Doctor Service
        working-directory: backend/doctor-service
        run: mvn clean package -DskipTests

      - name: Build Appointment Service
        working-directory: backend/appointment-service
        run: mvn clean package -DskipTests

      - name: Build API Gateway
        working-directory: backend/api-gateway
        run: mvn clean package -DskipTests